# Generated by Django 4.2.8 on 2024-03-01 16:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedoutlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 21, 34, 36, 41504)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 21, 34, 36, 41504)),
        ),
        migrations.AlterField(
            model_name='wastage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 1, 21, 34, 36, 41504)),
        ),
    ]
