# Generated by Django 4.2.8 on 2024-02-26 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedoutlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 0, 12, 8, 426083)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 0, 12, 8, 426083)),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='wastage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 27, 0, 12, 8, 425077)),
        ),
    ]
