# Generated by Django 4.2.8 on 2024-01-06 11:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0002_alter_checkedoutlog_created_at_alter_log_created_at_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subcategory',
            old_name='name',
            new_name='name_sub',
        ),
        migrations.AlterField(
            model_name='checkedoutlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 16, 44, 56, 653350)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 16, 44, 56, 653350)),
        ),
        migrations.AlterField(
            model_name='wastage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 16, 44, 56, 653350)),
        ),
    ]
