# Generated by Django 4.2.8 on 2024-01-06 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0003_rename_name_subcategory_name_sub_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedoutlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 17, 17, 13, 871644)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 17, 17, 13, 871644)),
        ),
        migrations.AlterField(
            model_name='wastage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 17, 17, 13, 871644)),
        ),
    ]
