# Generated by Django 4.2.8 on 2024-03-06 13:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0004_alter_checkedoutlog_created_at_alter_log_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedoutlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 19, 21, 35, 258984)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 19, 21, 35, 258984)),
        ),
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='wastage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 6, 19, 21, 35, 257981)),
        ),
    ]
