# Generated by Django 4.2.8 on 2024-01-06 13:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0006_product_actual_price_product_available_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedoutlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 18, 53, 57, 677185)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 18, 53, 57, 677185)),
        ),
        migrations.AlterField(
            model_name='product',
            name='actual_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='available_price',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='wastage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 6, 18, 53, 57, 677185)),
        ),
    ]
