# Generated by Django 4.2.8 on 2024-01-06 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0008_product_is_active_alter_checkedoutlog_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkedoutlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 0, 54, 45, 982732)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 0, 54, 45, 982732)),
        ),
        migrations.AlterField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='wastage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 7, 0, 54, 45, 982732)),
        ),
    ]
