# Generated by Django 4.2.8 on 2024-03-18 13:05

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0008_alter_checkedoutlog_created_at_alter_log_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='wastageadmindashboard',
            name='sub_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invention.subcategory'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkedoutlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 18, 35, 46, 339759)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 18, 35, 46, 339759)),
        ),
        migrations.AlterField(
            model_name='wastage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 18, 35, 46, 338760)),
        ),
        migrations.AlterField(
            model_name='wastageadmindashboard',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 18, 35, 46, 340759)),
        ),
    ]
