# Generated by Django 4.2.8 on 2024-03-18 15:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0009_wastageadmindashboard_sub_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wastageadmindashboard',
            name='sub_category',
        ),
        migrations.AlterField(
            model_name='checkedoutlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 21, 19, 39, 887933)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 21, 19, 39, 887933)),
        ),
        migrations.AlterField(
            model_name='wastage',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 21, 19, 39, 872292)),
        ),
        migrations.AlterField(
            model_name='wastageadmindashboard',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 21, 19, 39, 888894)),
        ),
    ]
