# Generated by Django 4.2.8 on 2024-03-18 16:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('invention', '0010_remove_wastageadmindashboard_sub_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='wastage',
            old_name='user',
            new_name='created_by',
        ),
        migrations.RemoveField(
            model_name='wastage',
            name='category',
        ),
        migrations.RemoveField(
            model_name='wastage',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='wastage',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='wastage',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='wastage',
            name='reason',
        ),
        migrations.AddField(
            model_name='wastage',
            name='wastage_user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='invention.wastageadmindashboard'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='checkedoutlog',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 21, 44, 38, 458277)),
        ),
        migrations.AlterField(
            model_name='log',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 21, 44, 38, 458277)),
        ),
        migrations.AlterField(
            model_name='wastageadmindashboard',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 3, 18, 21, 44, 38, 458277)),
        ),
    ]
